### ISSUE TITLE
A general question for CMAF Ingest

### ISSUE THREAD

**Issue by ggnull35** [Dash-Industry-Forum/CMAF-Conformance#58] opened 2021-01-18 19:53 UTC
Hi,

I checked the spec documents and I couldnt be sure for HTTP Pull CMAF compliance.
Can Ingest source (encoder) put the chunks on storage and can CDN HTTP Pull these chunks ? 
Is this a valid approach.

Kind Regards,

**Comment by dsilhavy** [comment] 2022-02-02 14:04
Duplicate of https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/534

**Closed by dsilhavy** 2022-02-02 14:04 UTC
